### ISSUE TITLE
已经翻译完成 edition guide

### ISSUE THREAD

**Issue by sunhuachuang** [rust-lang-cn/rust-translation-guide#1]
官方地址： https://github.com/rust-lang-nursery/edition-guide
不知是否能够加入到项目组中？

**Comment by sunhuachuang** [comment]
@aakloxu @ericjjj

**Comment by sunhuachuang** [comment]
https://github.com/sunhuachuang/edition-guide-cn/tree/master

**Comment by aaranxu** [comment]
非常感谢，欢迎加入 `rust-lang-cn` ，我看了你翻译的内容很不错，非常欢迎加入到项目中，让大家集时看到有关内容。同时也欢迎您本人加入到项目中，我本人也是出于个人兴趣爱好推动 Rust 在中国的的本土化工作，如果可以的话，非常乐于看到更多朋友加进来。

**Comment by sunhuachuang** [comment]
可以啊

**Comment by aaranxu** [comment]
已邀请，欢迎加入~

**Comment by aaranxu** [comment]
访问 <https://github.com/rust-lang-cn> 链接可以见到邀请链接，欢迎~
