### ISSUE TITLE
我翻译了 Rust-API-Guidelines 和 About The Little Book of Rust Macros (Updated Version)  能否加入 RustWiki

### ISSUE THREAD

**Issue by zjp-CN** [rust-lang-cn/rust-translation-guide#3]
地址：

[https://github.com/zjp-CN/api-guidelines](https://github.com/zjp-CN/api-guidelines)

[https://github.com/zjp-CN/tlborm](https://github.com/zjp-CN/tlborm)

**Comment by ZhangHanDong** [comment]
应该可以吧

**Comment by qsdgy** [comment]
https://github.com/zjp-CN/api-guidelines 这个项目没法提issue，有个翻译问题丢在这里吧。
第二章 `给数据结构实现 Serde 的 Serialize 和 Deserialize trait` 一节中，

原文 
> It would be completely reasonable for somebody to want to read in a LinkedHashMap or IpAddr from a JSON file, or send one over IPC to another process.

译文
> 从 JSON 中读取 LinkedHashMap 和 IpAddr ， 或者通过 IPC 发送其中一种数据到另一个进程 都显然十分不合理

意思相反。

原文
> `If a crate does not already depend on Serde for other reasons`

译文
> `出于某些原因，某个 crate 不再依赖 Serde`

建议改为
> `出于某些原因，某个 crate 还没有把 Serde 作为依赖`

 @zjp-CN

**Comment by zjp-CN** [comment]
@qsdgy 
我现在开了 issue 。
已经解决了。
见 https://github.com/zjp-CN/api-guidelines/issues/2
